// constants/pakistaniFoods.ts

export type FoodItem = {
  id: string;
  name: string;
  calories: number; // per serving
  serving: string; // what "1 serving" means
  category: FoodCategory;
  protein?: number; // grams (optional for now)
  carbs?: number; // grams
  fat?: number; // grams
};

export type FoodCategory =
  | "bread"
  | "rice"
  | "dal"
  | "curry"
  | "chicken"
  | "beef"
  | "snack"
  | "drink"
  | "dessert"
  | "breakfast"
  | "vegetable"
  | "fruit"
  | "dairy";

// Category display config — icon + label for UI
export const FOOD_CATEGORIES: Record<
  FoodCategory,
  { label: string; emoji: string }
> = {
  bread: { label: "Bread & Roti", emoji: "🫓" },
  rice: { label: "Rice", emoji: "🍚" },
  dal: { label: "Dal", emoji: "🫘" },
  curry: { label: "Curry", emoji: "🍛" },
  chicken: { label: "Chicken", emoji: "🍗" },
  beef: { label: "Beef", emoji: "🥩" },
  snack: { label: "Snacks", emoji: "🥨" },
  drink: { label: "Drinks", emoji: "🥤" },
  dessert: { label: "Desserts", emoji: "🍮" },
  breakfast: { label: "Breakfast", emoji: "🍳" },
  vegetable: { label: "Vegetables", emoji: "🥦" },
  fruit: { label: "Fruits", emoji: "🍎" },
  dairy: { label: "Dairy", emoji: "🥛" },
};

export const PAKISTANI_FOODS: FoodItem[] = [
  // ─── BREAD & ROTI ──────────────────────────────────────
  {
    id: "pb001",
    name: "Chapati (Phulka)",
    calories: 70,
    serving: "1 small roti (30g)",
    category: "bread",
    protein: 2,
    carbs: 15,
    fat: 0.5,
  },
  {
    id: "pb002",
    name: "Roti (Tandoor)",
    calories: 120,
    serving: "1 medium roti (50g)",
    category: "bread",
    protein: 4,
    carbs: 25,
    fat: 1,
  },
  {
    id: "pb003",
    name: "Paratha (Plain)",
    calories: 260,
    serving: "1 paratha (80g)",
    category: "bread",
    protein: 5,
    carbs: 32,
    fat: 12,
  },
  {
    id: "pb004",
    name: "Aloo Paratha",
    calories: 320,
    serving: "1 paratha with filling (120g)",
    category: "bread",
    protein: 6,
    carbs: 45,
    fat: 12,
  },
  {
    id: "pb005",
    name: "Puri",
    calories: 180,
    serving: "1 puri (50g)",
    category: "bread",
    protein: 3,
    carbs: 22,
    fat: 9,
  },
  {
    id: "pb006",
    name: "Naan (Plain)",
    calories: 265,
    serving: "1 naan (90g)",
    category: "bread",
    protein: 9,
    carbs: 50,
    fat: 4,
  },
  {
    id: "pb007",
    name: "Naan (Butter)",
    calories: 320,
    serving: "1 naan with butter (100g)",
    category: "bread",
    protein: 9,
    carbs: 50,
    fat: 10,
  },
  {
    id: "pb008",
    name: "Sheermal",
    calories: 280,
    serving: "1 piece (90g)",
    category: "bread",
    protein: 7,
    carbs: 48,
    fat: 8,
  },

  // ─── RICE ──────────────────────────────────────────────
  {
    id: "pr001",
    name: "Plain Rice (Chawal)",
    calories: 206,
    serving: "1 cup cooked (180g)",
    category: "rice",
    protein: 4,
    carbs: 45,
    fat: 0.5,
  },
  {
    id: "pr002",
    name: "Chicken Biryani",
    calories: 420,
    serving: "1 plate (300g)",
    category: "rice",
    protein: 22,
    carbs: 52,
    fat: 14,
  },
  {
    id: "pr003",
    name: "Beef Biryani",
    calories: 460,
    serving: "1 plate (300g)",
    category: "rice",
    protein: 24,
    carbs: 52,
    fat: 17,
  },
  {
    id: "pr004",
    name: "Pulao (Matar)",
    calories: 280,
    serving: "1 cup (200g)",
    category: "rice",
    protein: 7,
    carbs: 48,
    fat: 7,
  },
  {
    id: "pr005",
    name: "Yakhni Pulao",
    calories: 340,
    serving: "1 plate (250g)",
    category: "rice",
    protein: 18,
    carbs: 46,
    fat: 10,
  },
  {
    id: "pr006",
    name: "Khichdi",
    calories: 220,
    serving: "1 cup (200g)",
    category: "rice",
    protein: 8,
    carbs: 40,
    fat: 4,
  },
  {
    id: "pr007",
    name: "Zeera Rice",
    calories: 230,
    serving: "1 cup (180g)",
    category: "rice",
    protein: 4,
    carbs: 46,
    fat: 4,
  },

  // ─── DAL ───────────────────────────────────────────────
  {
    id: "pd001",
    name: "Dal Chawal",
    calories: 380,
    serving: "1 plate dal + rice (350g)",
    category: "dal",
    protein: 14,
    carbs: 68,
    fat: 6,
  },
  {
    id: "pd002",
    name: "Dal Makhani",
    calories: 198,
    serving: "1 cup (200g)",
    category: "dal",
    protein: 10,
    carbs: 24,
    fat: 7,
  },
  {
    id: "pd003",
    name: "Masoor Dal",
    calories: 168,
    serving: "1 cup cooked (200g)",
    category: "dal",
    protein: 12,
    carbs: 28,
    fat: 1,
  },
  {
    id: "pd004",
    name: "Chana Dal",
    calories: 180,
    serving: "1 cup cooked (200g)",
    category: "dal",
    protein: 11,
    carbs: 30,
    fat: 2,
  },
  {
    id: "pd005",
    name: "Moong Dal",
    calories: 147,
    serving: "1 cup cooked (200g)",
    category: "dal",
    protein: 10,
    carbs: 25,
    fat: 1,
  },
  {
    id: "pd006",
    name: "Chana Masala",
    calories: 210,
    serving: "1 cup (200g)",
    category: "dal",
    protein: 11,
    carbs: 32,
    fat: 5,
  },

  // ─── CHICKEN ───────────────────────────────────────────
  {
    id: "pc001",
    name: "Chicken Karahi",
    calories: 320,
    serving: "1 serving (200g)",
    category: "chicken",
    protein: 30,
    carbs: 8,
    fat: 18,
  },
  {
    id: "pc002",
    name: "Chicken Handi",
    calories: 350,
    serving: "1 serving (200g)",
    category: "chicken",
    protein: 28,
    carbs: 12,
    fat: 20,
  },
  {
    id: "pc003",
    name: "Tandoori Chicken",
    calories: 260,
    serving: "1 piece leg+thigh (200g)",
    category: "chicken",
    protein: 35,
    carbs: 4,
    fat: 12,
  },
  {
    id: "pc004",
    name: "Chicken Tikka",
    calories: 240,
    serving: "4 pieces (150g)",
    category: "chicken",
    protein: 32,
    carbs: 3,
    fat: 11,
  },
  {
    id: "pc005",
    name: "Chicken Korma",
    calories: 380,
    serving: "1 serving (200g)",
    category: "chicken",
    protein: 26,
    carbs: 10,
    fat: 26,
  },
  {
    id: "pc006",
    name: "Chicken Pulao",
    calories: 360,
    serving: "1 plate (280g)",
    category: "chicken",
    protein: 22,
    carbs: 44,
    fat: 12,
  },
  {
    id: "pc007",
    name: "Murgh Cholay",
    calories: 290,
    serving: "1 serving (220g)",
    category: "chicken",
    protein: 24,
    carbs: 22,
    fat: 12,
  },
  {
    id: "pc008",
    name: "Chicken Shami Kebab",
    calories: 140,
    serving: "2 kebabs (100g)",
    category: "chicken",
    protein: 14,
    carbs: 8,
    fat: 6,
  },

  // ─── BEEF ──────────────────────────────────────────────
  {
    id: "pbf001",
    name: "Beef Karahi",
    calories: 360,
    serving: "1 serving (200g)",
    category: "beef",
    protein: 28,
    carbs: 6,
    fat: 24,
  },
  {
    id: "pbf002",
    name: "Nihari",
    calories: 380,
    serving: "1 bowl (250g)",
    category: "beef",
    protein: 30,
    carbs: 12,
    fat: 24,
  },
  {
    id: "pbf003",
    name: "Paya (Trotters)",
    calories: 220,
    serving: "1 bowl (200g)",
    category: "beef",
    protein: 20,
    carbs: 4,
    fat: 14,
  },
  {
    id: "pbf004",
    name: "Seekh Kebab",
    calories: 190,
    serving: "2 seekh (120g)",
    category: "beef",
    protein: 20,
    carbs: 4,
    fat: 10,
  },
  {
    id: "pbf005",
    name: "Beef Kofta",
    calories: 280,
    serving: "4 koftas (160g)",
    category: "beef",
    protein: 22,
    carbs: 8,
    fat: 18,
  },
  {
    id: "pbf006",
    name: "Haleem",
    calories: 280,
    serving: "1 bowl (250g)",
    category: "beef",
    protein: 18,
    carbs: 28,
    fat: 10,
  },
  {
    id: "pbf007",
    name: "Beef Bihari Kebab",
    calories: 220,
    serving: "2 pieces (130g)",
    category: "beef",
    protein: 22,
    carbs: 4,
    fat: 13,
  },

  // ─── BREAKFAST ─────────────────────────────────────────
  {
    id: "pbr001",
    name: "Anda (Boiled Egg)",
    calories: 77,
    serving: "1 large egg (50g)",
    category: "breakfast",
    protein: 6,
    carbs: 1,
    fat: 5,
  },
  {
    id: "pbr002",
    name: "Anda Bhurji (Scrambled)",
    calories: 180,
    serving: "2 eggs scrambled (110g)",
    category: "breakfast",
    protein: 12,
    carbs: 2,
    fat: 14,
  },
  {
    id: "pbr003",
    name: "Omelette (Plain)",
    calories: 154,
    serving: "2 egg omelette (100g)",
    category: "breakfast",
    protein: 11,
    carbs: 1,
    fat: 12,
  },
  {
    id: "pbr004",
    name: "Halwa Puri",
    calories: 580,
    serving: "1 plate — 2 puri + halwa (250g)",
    category: "breakfast",
    protein: 8,
    carbs: 78,
    fat: 26,
  },
  {
    id: "pbr005",
    name: "Nashta Paratha + Egg",
    calories: 440,
    serving: "1 paratha + 1 egg (180g)",
    category: "breakfast",
    protein: 14,
    carbs: 38,
    fat: 24,
  },
  {
    id: "pbr006",
    name: "Doodh Patti Chai",
    calories: 120,
    serving: "1 cup strong milk tea (200ml)",
    category: "breakfast",
    protein: 4,
    carbs: 14,
    fat: 5,
  },
  {
    id: "pbr007",
    name: "Lassi (Sweet)",
    calories: 180,
    serving: "1 glass (250ml)",
    category: "breakfast",
    protein: 6,
    carbs: 28,
    fat: 5,
  },
  {
    id: "pbr008",
    name: "Lassi (Salted)",
    calories: 110,
    serving: "1 glass (250ml)",
    category: "breakfast",
    protein: 6,
    carbs: 12,
    fat: 4,
  },

  // ─── CURRY & VEGETABLE ─────────────────────────────────
  {
    id: "pv001",
    name: "Aloo Gosht",
    calories: 310,
    serving: "1 serving (220g)",
    category: "curry",
    protein: 20,
    carbs: 18,
    fat: 18,
  },
  {
    id: "pv002",
    name: "Saag (Palak)",
    calories: 140,
    serving: "1 cup (200g)",
    category: "vegetable",
    protein: 5,
    carbs: 14,
    fat: 7,
  },
  {
    id: "pv003",
    name: "Aloo Matar",
    calories: 190,
    serving: "1 cup (200g)",
    category: "vegetable",
    protein: 5,
    carbs: 28,
    fat: 7,
  },
  {
    id: "pv004",
    name: "Bhindi Masala",
    calories: 130,
    serving: "1 cup (180g)",
    category: "vegetable",
    protein: 3,
    carbs: 16,
    fat: 6,
  },
  {
    id: "pv005",
    name: "Baingan Bharta",
    calories: 150,
    serving: "1 cup (200g)",
    category: "vegetable",
    protein: 3,
    carbs: 18,
    fat: 7,
  },
  {
    id: "pv006",
    name: "Kofta Curry",
    calories: 300,
    serving: "1 serving — 4 koftas (220g)",
    category: "curry",
    protein: 18,
    carbs: 12,
    fat: 20,
  },
  {
    id: "pv007",
    name: "Daal Gosht",
    calories: 340,
    serving: "1 bowl (250g)",
    category: "curry",
    protein: 22,
    carbs: 28,
    fat: 14,
  },
  {
    id: "pv008",
    name: "Shahi Paneer",
    calories: 280,
    serving: "1 cup (200g)",
    category: "curry",
    protein: 12,
    carbs: 14,
    fat: 20,
  },

  // ─── SNACKS ────────────────────────────────────────────
  {
    id: "ps001",
    name: "Samosa (Aloo)",
    calories: 130,
    serving: "1 medium samosa (60g)",
    category: "snack",
    protein: 3,
    carbs: 18,
    fat: 6,
  },
  {
    id: "ps002",
    name: "Pakora (Mix)",
    calories: 80,
    serving: "3 pieces (50g)",
    category: "snack",
    protein: 3,
    carbs: 10,
    fat: 4,
  },
  {
    id: "ps003",
    name: "Dahi Bhalla",
    calories: 180,
    serving: "2 pieces (150g)",
    category: "snack",
    protein: 7,
    carbs: 28,
    fat: 4,
  },
  {
    id: "ps004",
    name: "Chaat (Aloo)",
    calories: 160,
    serving: "1 plate (150g)",
    category: "snack",
    protein: 4,
    carbs: 26,
    fat: 5,
  },
  {
    id: "ps005",
    name: "Gol Gappay (6 pieces)",
    calories: 120,
    serving: "6 gol gappay (80g)",
    category: "snack",
    protein: 2,
    carbs: 22,
    fat: 3,
  },
  {
    id: "ps006",
    name: "Bread Pakora",
    calories: 210,
    serving: "1 piece (90g)",
    category: "snack",
    protein: 6,
    carbs: 26,
    fat: 9,
  },
  {
    id: "ps007",
    name: "Nimko (Spicy Mix)",
    calories: 140,
    serving: "1 small pack (40g)",
    category: "snack",
    protein: 4,
    carbs: 18,
    fat: 6,
  },
  {
    id: "ps008",
    name: "Roasted Chana",
    calories: 120,
    serving: "¼ cup (30g)",
    category: "snack",
    protein: 6,
    carbs: 18,
    fat: 3,
  },

  // ─── DESSERTS ──────────────────────────────────────────
  {
    id: "pds001",
    name: "Kheer",
    calories: 220,
    serving: "1 bowl (200g)",
    category: "dessert",
    protein: 6,
    carbs: 38,
    fat: 6,
  },
  {
    id: "pds002",
    name: "Gulab Jamun",
    calories: 150,
    serving: "2 pieces (80g)",
    category: "dessert",
    protein: 3,
    carbs: 28,
    fat: 4,
  },
  {
    id: "pds003",
    name: "Gajar Halwa",
    calories: 280,
    serving: "1 cup (150g)",
    category: "dessert",
    protein: 5,
    carbs: 40,
    fat: 12,
  },
  {
    id: "pds004",
    name: "Seviyan (Vermicelli)",
    calories: 240,
    serving: "1 bowl (180g)",
    category: "dessert",
    protein: 5,
    carbs: 38,
    fat: 8,
  },
  {
    id: "pds005",
    name: "Sooji Halwa",
    calories: 260,
    serving: "1 cup (150g)",
    category: "dessert",
    protein: 4,
    carbs: 42,
    fat: 10,
  },
  {
    id: "pds006",
    name: "Rabri",
    calories: 300,
    serving: "1 small bowl (150g)",
    category: "dessert",
    protein: 8,
    carbs: 36,
    fat: 14,
  },
  {
    id: "pds007",
    name: "Barfi (Plain)",
    calories: 160,
    serving: "2 pieces (50g)",
    category: "dessert",
    protein: 4,
    carbs: 24,
    fat: 6,
  },

  // ─── DRINKS ────────────────────────────────────────────
  {
    id: "pdr001",
    name: "Chai (Milk Tea)",
    calories: 60,
    serving: "1 cup light tea (150ml)",
    category: "drink",
    protein: 2,
    carbs: 8,
    fat: 2,
  },
  {
    id: "pdr002",
    name: "Rooh Afza Sharbat",
    calories: 130,
    serving: "1 glass (250ml)",
    category: "drink",
    protein: 0,
    carbs: 32,
    fat: 0,
  },
  {
    id: "pdr003",
    name: "Mango Juice (Packed)",
    calories: 120,
    serving: "1 glass (250ml)",
    category: "drink",
    protein: 1,
    carbs: 30,
    fat: 0,
  },
  {
    id: "pdr004",
    name: "Sugarcane Juice",
    calories: 110,
    serving: "1 glass (250ml)",
    category: "drink",
    protein: 0,
    carbs: 28,
    fat: 0,
  },
  {
    id: "pdr005",
    name: "Nimbu Pani",
    calories: 40,
    serving: "1 glass with sugar (250ml)",
    category: "drink",
    protein: 0,
    carbs: 10,
    fat: 0,
  },
  {
    id: "pdr006",
    name: "Water",
    calories: 0,
    serving: "1 glass (250ml)",
    category: "drink",
    protein: 0,
    carbs: 0,
    fat: 0,
  },

  // ─── FRUITS ────────────────────────────────────────────
  {
    id: "pfr001",
    name: "Mango (Aam)",
    calories: 100,
    serving: "1 medium mango (150g)",
    category: "fruit",
    protein: 1,
    carbs: 25,
    fat: 0,
  },
  {
    id: "pfr002",
    name: "Banana (Kela)",
    calories: 89,
    serving: "1 medium banana (100g)",
    category: "fruit",
    protein: 1,
    carbs: 23,
    fat: 0,
  },
  {
    id: "pfr003",
    name: "Apple (Seb)",
    calories: 72,
    serving: "1 medium apple (130g)",
    category: "fruit",
    protein: 0,
    carbs: 19,
    fat: 0,
  },
  {
    id: "pfr004",
    name: "Guava (Amrood)",
    calories: 68,
    serving: "1 medium guava (100g)",
    category: "fruit",
    protein: 3,
    carbs: 14,
    fat: 1,
  },
  {
    id: "pfr005",
    name: "Dates (Khajoor)",
    calories: 110,
    serving: "4 dates (40g)",
    category: "fruit",
    protein: 1,
    carbs: 30,
    fat: 0,
  },

  // ─── DAIRY ─────────────────────────────────────────────
  {
    id: "pdy001",
    name: "Dahi (Plain Yogurt)",
    calories: 100,
    serving: "1 cup (200g)",
    category: "dairy",
    protein: 8,
    carbs: 10,
    fat: 4,
  },
  {
    id: "pdy002",
    name: "Doodh (Full Fat Milk)",
    calories: 150,
    serving: "1 glass (240ml)",
    category: "dairy",
    protein: 8,
    carbs: 12,
    fat: 8,
  },
  {
    id: "pdy003",
    name: "Paneer",
    calories: 265,
    serving: "100g",
    category: "dairy",
    protein: 18,
    carbs: 4,
    fat: 20,
  },
  {
    id: "pdy004",
    name: "Makhan (Butter)",
    calories: 102,
    serving: "1 tablespoon (14g)",
    category: "dairy",
    protein: 0,
    carbs: 0,
    fat: 12,
  },
];

// ─── SEARCH HELPER ────────────────────────────────────────
// Returns foods matching the search query
// Searches by name (case insensitive)

export function searchFoods(query: string): FoodItem[] {
  if (!query.trim()) return PAKISTANI_FOODS;
  const q = query.toLowerCase().trim();
  return PAKISTANI_FOODS.filter(
    (food) =>
      food.name.toLowerCase().includes(q) ||
      food.category.toLowerCase().includes(q),
  );
}

// Returns foods filtered by category
export function getFoodsByCategory(category: FoodCategory): FoodItem[] {
  return PAKISTANI_FOODS.filter((f) => f.category === category);
}
